version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: rag-backend:latest
    container_name: rag-backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: rag-ui:latest
    container_name: rag-ui
    command: streamlit run ui.py
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      API_BASE_URL: http://backend:8000
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

